/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 robot.glb --transform 
Files: robot.glb [8.94MB] > D:\Code\robot-landingpage\public\robot-transformed.glb [1.44MB] (84%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/robot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Computer_Head.geometry} material={materials.Computer} />
      <mesh geometry={nodes.Angry.geometry} material={materials.Expression} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Parts} position={[1.995, 0.04, 0.378]} rotation={[-0.41, 0, 0.438]} scale={0.974} />
      <mesh name="Neutral" geometry={nodes.Neutral.geometry} material={materials.Expression} morphTargetDictionary={nodes.Neutral.morphTargetDictionary} morphTargetInfluences={nodes.Neutral.morphTargetInfluences} />
      <mesh name="Smile" geometry={nodes.Smile.geometry} material={materials.Expression} morphTargetDictionary={nodes.Smile.morphTargetDictionary} morphTargetInfluences={nodes.Smile.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/robot-transformed.glb')
