/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 robot.glb --transform 
Files: robot.glb [5.24MB] > D:\Code\robot-landingpage\public\robot-transformed.glb [1.09MB] (79%)
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Robot(props) {
  const { nodes, materials } = useGLTF('/robot-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Computer_Head.geometry}
        material={materials.Television}
      />
      <mesh geometry={nodes.Angry.geometry} material={materials.Expression} />
      <mesh
        name="Neutral"
        geometry={nodes.Neutral.geometry}
        material={materials.Expression}
        morphTargetDictionary={nodes.Neutral.morphTargetDictionary}
        morphTargetInfluences={nodes.Neutral.morphTargetInfluences}
      />
      <mesh
        name="Smile"
        geometry={nodes.Smile.geometry}
        material={materials.Expression}
        morphTargetDictionary={nodes.Smile.morphTargetDictionary}
        morphTargetInfluences={nodes.Smile.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload('/robot-transformed.glb');
